gpu: 0
seed: 2025
train_h5_path: /mnt/scratchpad/xzt_ma/phase_0_exp_a/ssl_train.h5
val_h5_path: /mnt/scratchpad/xzt_ma/phase_0_exp_a/ssl_val.h5
test_h5_path: /mnt/scratchpad/xzt_ma/phase_0_exp_a/ssl_test.h5
batch_size: 64
ckpt_save_dir: checkpoints                                                       # The save directory for the classifier
ckpt_filename: ssl_cnn.pt
input_dim: 4096
hidden_dim: 512
embed_dim: 128
enable_channel_circular_padding: False
num_classes: 4
classifier: EMGFeatureCNN
lr: 0.0001
patience: 7
wandb_project: Llama4EMG_Ninapro_DB5
exp_name: Phase_0_exp_a_no_bp_filter_no_rectify_ssl_cnn
epochs: 100
trainer: CNN4EMGTrainer
enable_balance_labels: True
downsample_target_ratio: 1.5                                   # the target number of samples for the downsample_label is max(other_class_count) * target_ratio