gpu: 0
seed: 2026
train_h5_path: /mnt/scratchpad/xzt_ma/phase_1_exp_1/supervised_train.h5
val_h5_path: /mnt/scratchpad/xzt_ma/phase_1_exp_1/supervised_val.h5
test_h5_path: /mnt/scratchpad/xzt_ma/phase_1_exp_1/supervised_test.h5
batch_size: 64
ckpt_save_dir: checkpoints                                                       # The save directory for the classifier
ckpt_filename: ssl_cnn.pt
conv1_channels: 32
conv2_channels: 64
enable_channel_circular_padding: False
num_classes: 7
classifier: EMGPureCNN
lr: 0.0001
patience: 7
wandb_project: Llama4EMG_Ninapro_DB5
exp_name: Phase_2_exp_1_pure_cnn
epochs: 100
trainer: CNN4EMGTrainer
enable_balance_labels: True
downsample_target_ratio: 1.0                                   # the target number of samples for the downsample_label is max(other_class_count) * target_ratio