gpu: 0
seed: 2025
train_h5_path: h5_dir/ssl_train.h5
val_h5_path: h5_dir/ssl_val.h5
test_h5_path: h5_dir/ssl_test.h5
batch_size: 64
ckpt_save_dir: ./checkpoints                                                       # The save directory for the classifier
ckpt_filename: cnn.pt
input_dim: 4096
hidden_dim: 512
embed_dim: 128
num_classes: 3
classifier: EMGFeatureCNN
lr: 0.0001
patience: 5
wandb_project: Llama4EMG_Ninapro_DB5
exp_name: feature_classifier
epochs: 100
trainer: CNN4EMGTrainer